"""updated chapter, creature, even, faction, item, location, plot, relationship, system, world

Revision ID: 19e76915174c
Revises: 99a2196ad9e7
Create Date: 2024-07-09 18:53:29.831124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e76915174c'
down_revision = '99a2196ad9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('creature_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('magic_system_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('faction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faction', ['faction_id'], ['id'])
        batch_op.create_foreign_key(None, 'world', ['world_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'])
        batch_op.create_foreign_key(None, 'system', ['magic_system_id'], ['id'])
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'creature', ['creature_id'], ['id'])

    with op.batch_alter_table('creature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('align', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('abilities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weapons', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('armor', sa.Text(), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('faction_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faction', ['faction_id'], ['id'])
        batch_op.create_foreign_key(None, 'plot', ['plot_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'])

    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_neutral', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_good', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_evil', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_chaotic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_lawful', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alignment', sa.String(length=50), nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enchantment', sa.String(length=50), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=50), nullable=False))

    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('published_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_romantic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_supportive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_rival', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_ally', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_conflict', sa.Boolean(), nullable=True))

    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basis', sa.Text(), nullable=True))

    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_period', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('setting', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('flora', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fauna', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('magical_system', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_column('magical_system')
        batch_op.drop_column('fauna')
        batch_op.drop_column('flora')
        batch_op.drop_column('humidity')
        batch_op.drop_column('temperature')
        batch_op.drop_column('setting')
        batch_op.drop_column('time_period')

    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_column('basis')

    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_column('is_conflict')
        batch_op.drop_column('is_ally')
        batch_op.drop_column('is_rival')
        batch_op.drop_column('is_supportive')
        batch_op.drop_column('is_romantic')
        batch_op.drop_column('level')

    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_column('published_date')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('word_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('genre')
        batch_op.drop_column('status')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('enchantment')
        batch_op.drop_column('value')
        batch_op.drop_column('weight')

    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.drop_column('alignment')
        batch_op.drop_column('is_lawful')
        batch_op.drop_column('is_chaotic')
        batch_op.drop_column('is_evil')
        batch_op.drop_column('is_good')
        batch_op.drop_column('is_neutral')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plot_id')
        batch_op.drop_column('faction_id')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('creature', schema=None) as batch_op:
        batch_op.drop_column('armor')
        batch_op.drop_column('weapons')
        batch_op.drop_column('abilities')
        batch_op.drop_column('align')
        batch_op.drop_column('role')
        batch_op.drop_column('age')
        batch_op.drop_column('size')
        batch_op.drop_column('species')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faction_id')
        batch_op.drop_column('magic_system_id')
        batch_op.drop_column('event_id')
        batch_op.drop_column('creature_id')
        batch_op.drop_column('location_id')
        batch_op.drop_column('world_id')

    # ### end Alembic commands ###
