"""Character

Revision ID: 99a2196ad9e7
Revises: 
Create Date: 2024-07-09 18:42:12.298312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a2196ad9e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('class_', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('deity', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('alignment', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('strength', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dexterity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('constitution', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('intelligence', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wisdom', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('charisma', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('experience_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('background', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('personality', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('ideal', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('bonds', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('flaws', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('flaws')
        batch_op.drop_column('bonds')
        batch_op.drop_column('ideal')
        batch_op.drop_column('personality')
        batch_op.drop_column('background')
        batch_op.drop_column('experience_points')
        batch_op.drop_column('charisma')
        batch_op.drop_column('wisdom')
        batch_op.drop_column('intelligence')
        batch_op.drop_column('constitution')
        batch_op.drop_column('dexterity')
        batch_op.drop_column('strength')
        batch_op.drop_column('alignment')
        batch_op.drop_column('age')
        batch_op.drop_column('deity')
        batch_op.drop_column('class_')
        batch_op.drop_column('race')

    # ### end Alembic commands ###
